name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build maven project
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Run Maven tests
      run: mvn clean test

    - name: Package Maven project
      run: mvn clean package -DskipTests

    -name: Upload artifact
      uses: actions/upload-artifact@v3
        with:
        name: my-artifact
        path: target/*.jar